package com.udacity.gradle.builditbigger.models

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 * A class used to bundle groups of posts
 * @constructor is used to create an instance of the class with all property values determined
 *
 * @property title, the title of the collection, can be changed by user
 * @property author, the creator of the collection, user names can be changed
 * @property restricted, boolean value determines if other users can see the posts in the collection
 * @property timeStamp, the time when the collection was created
 * @property uid, the author's user id number, generated by firebase
 * @property genreId, the unique id for the collection generated by firebase
 *
 */

@Parcelize
data class Collection(var title: String, var author: String, var restricted: Boolean,
                      val timeStamp: Long, val uid: String, val genreId: String) : Parcelable {

    override fun equals(other: Any?): Boolean {
        return (other is Collection) && genreId == other.genreId
    }

}
