package com.udacity.gradle.builditbigger.models

/**
 * A class used to create comments under posts
 *
 * @property hilarityUserUID, the commentor's unique user ID
 * @property timeDate, the time when the comment was created
 * @property commentContent, the body of the text submitted as a comment
 * @property postUid, the id of the user who created the post
 * @property postPushId, the id of the post
 * @property commentId, the id of the comment, generated by firebase
 */

data class Comment(val hilarityUserUID: String, val timeDate: Long, var commentContent: String,
                   val postUid: String, val postPushId: String, val commentId: String)