package com.udacity.gradle.builditbigger.models

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 * A class used to model questions submitted in the forum
 *
 * @property question, the body of the text to be intertrepted as a question, editable
 * @property hilarityUserUID, the question submitter's id, generated by firebase
 * @property timeStamp, when the question was created
 * @property key, the forum question's id, generated by firebase
 */

@Parcelize
data class ForumQuestion(var question: String, val hilarityUserUID: String,
                         val timeStamp: Long, val key: String) : Parcelable {

    override fun equals(other: Any?): Boolean {
        return (other is ForumQuestion) && key == other.key
    }
}