package com.udacity.gradle.builditbigger.models

/**
 * A class that represents replies to forum questions
 *
 * @property hilarityUserUID, the replier's user id, generated by firebase
 * @property content, the body of the reply
 * @property timeStamp, when the reply was created
 * @property key, the forum reply's id, generate by firebase
 */

data class ForumReply(val hilarityUserUID: String, var content: String,
                      val timeStamp: Long, val key: String) {

    override fun equals(other: Any?): Boolean {
        return (other is ForumReply) && key == other.key
    }
}